### PR TITLE
Private to protected

### PR DESCRIPTION
**Pull request by cajpearce**
Changing some of the private/internal methods and classes to protected so that the API can be extended

### CODE REVIEW

**Comment by cajpearce** [comment]
It failed some tests - I have little experience with AppVeyor so far, so do not fully understand why.

**Comment by cajpearce** [comment]
are the test files still accessible?

**Comment by Lakritzator** [comment]
The tests of a pulll-request always fail due to the fact that the encrypted variables which contain my test user are not resolved for PRs, This makes testing impossible... 😄 
I will check it out later this week, now it's almost midnight.

Doesn't look bad, but I am actually more curious about what you are going to do with those changed, maybe it's something other people can use too?

**Comment by cajpearce** [comment]
Ha! Ok that makes more sense. That is fine, it is almost midday here so understand there is a timezone difference :-)

I'm hoping to make use of the [Confluence Questions Plugin API](https://docs.atlassian.com/confluence-questions/rest/resource_QuestionResource.html), and would rather try extend your class first before trying to code it again from scratch. I have a hunch that your Confluence Entities will be the same as the Question entities... Might save me a bunch of time!

**Comment by Lakritzator** [comment]
Hi Christopher,

Today, during me walking my dog, I had a bit of time to think about how the Dapplo.Confluence project (and also my Dapplo.Jira) can be extended. Your changes are far from wrong, but won't help us on the long term. As making field protected would help to make it possible to extend the ConfluenceApi, it would only work from a OOP perspective. But as soon as we want to add more functionality for a different plugin, we would have an issue... C# doesn't support "mixins".

So, we need a different solution. I was thinking about having the ConfluenceApi implement a few interfaces (**didn't decide on the naming yet**).

The factory method, Confluence.Create or something like that will return an:
IConfluenceApi -> having only the basic properties / methods, and one public Property called "Plugin" which returns an:
IConfluencePluginBase -> having publicly available properties / methods
You can than write your logic in form of extensions methods
```
public static class ConfluenceQuestionsExtensions {
  public static Task<IList<Question>> GetQuestionsAsync(this IConfluencePluginBase confluenceApi) {
    confluenceApi.PromoteContext();
    ... your logic
  }
```
Can you understand my point? I would be more than happy to let you make the changes, so you can tell you contributed :smiley:  

If you need some kind of context or configuration, so your static calls can use this or store something for "later", you can always use the IHttpRequestConfiguration. An example of an implementation of this interface can be found here: https://github.com/dapplo/Dapplo.HttpExtensions/blob/master/Dapplo.HttpExtensions/ContentConverter/StringConfiguration.cs
(You can just store pretty much everything, making it possible to have a specific interface to your logic which does not NEED to be used but allow the user to override certain behaviours)

An a usage example can be found here: https://github.com/dapplo/Dapplo.HttpExtensions/blob/master/Dapplo.HttpExtensions/ContentConverter/StringHttpContentConverter.cs#L110

Best wishes,
Robin

**Comment by Lakritzator** [comment]
I hope it's okay to close this PR, as the current API was changed not only to allow extensions but promote it. In fact, you can just "copy" an example like the "MiscExtensions" to see how it's done.

btw. if you have a specific need for functionality let me know.

**Pull request closed without merging**
