### PR TITLE
Add start for search with pagination support

### PR DESCRIPTION
**Pull request by tjouinrmld**
This is an API break, not sure how you want to handle it.
Also not sure how I can test this on your confluence

### CODE REVIEW

**Comment by Lakritzator** [comment]
I think it will make sense to move all the search parameters into their own class, which has helpers to simplify the usage. This will make the API less vulnerable to changes.

**Comment by Lakritzator** [comment]
My suggestion would be something like the following, maybe you can tell if that's okay for you.

```
        /// <summary>
        ///     Possible since 5.7
        ///     Search for issues, with a CQL (e.g. from a filter) see
        ///     <a href="https://docs.atlassian.com/confluence/REST/latest/#d2e4539">here</a>
        /// </summary>
        /// <param name="confluenceClient">IContentDomain to bind the extension method to</param>
        /// <param name="cqlClause">Confluence Query Language, like SQL, for the search</param>
        /// <param name="cqlContext">
        ///     the execution context for CQL functions, provides current space key and content id. If this is
        ///     not provided some CQL functions will not be available.
        /// </param>
        /// <param name="start">The number to start with, can be used for paging the results</param>
        /// <param name="limit">Maximum number of results returned, default is 20</param>
        /// <param name="expandSearch">The expand value for the search, when null the value from the ConfluenceClientConfig.ExpandSearch is taken</param>
        /// <param name="cancellationToken">CancellationToken</param>
        /// <returns>Result with content items</returns>
        public static Task<Result<Content>> SearchAsync(this IContentDomain confluenceClient, IFinalClause cqlClause, string cqlContext = null, int? start = 0, int? limit = 20, IEnumerable<string> expandSearch = null,
            CancellationToken cancellationToken = default)
        {
            var searchDetails = new SearchDetails(cqlClause);
            if (start.HasValue)
            {
                searchDetails.Start = start;
            }
            if (limit.HasValue)
            {
                searchDetails.Limit = limit;
            }
            if (cqlContext != null)
            {
                searchDetails.CqlContext = cqlContext;
            }
            if (expandSearch != null)
            {
                searchDetails.ExpandSearch = expandSearch;
            }
            return confluenceClient.SearchAsync(searchDetails, cancellationToken);
        }

        /// <summary>
        ///     Possible since 5.7
        ///     Search for issues, with a CQL (e.g. from a filter) see
        ///     <a href="https://docs.atlassian.com/confluence/REST/latest/#d2e4539">here</a>
        /// </summary>
        /// <param name="confluenceClient">IContentDomain to bind the extension method to</param>
        /// <param name="searchDetails">All the details needed for a search</param>
        /// <param name="cancellationToken">CancellationToken</param>
        /// <returns>Result with content items</returns>
        public static async Task<Result<Content>> SearchAsync(this IContentDomain confluenceClient, SearchDetails searchDetails, CancellationToken cancellationToken = default) {
            confluenceClient.Behaviour.MakeCurrent();

            var searchUri = confluenceClient.ConfluenceApiUri.AppendSegments("content", "search").ExtendQuery("cql", searchDetails.Cql);

            if (searchDetails.Limit.HasValue)
            {
                searchUri = searchUri.ExtendQuery("limit", searchDetails.Limit);
            }
            if (searchDetails.Start.HasValue)
            {
                searchUri = searchUri.ExtendQuery("start", searchDetails.Start);
            }

            var expand = string.Join(",", searchDetails.ExpandSearch ?? ConfluenceClientConfig.ExpandSearch ?? Enumerable.Empty<string>());
            if (!string.IsNullOrEmpty(expand))
            {
                searchUri = searchUri.ExtendQuery("expand", expand);
            }

            if (searchDetails.CqlContext != null)
            {
                searchUri = searchUri.ExtendQuery("cqlcontext", searchDetails.CqlContext);
            }

            var response = await searchUri.GetAsAsync<HttpResponse<Result<Content>, Error>>(cancellationToken).ConfigureAwait(false);
            return response.HandleErrors();
        }
```

And I've added a new class "SearchDetails":

```
// Copyright (c) Dapplo and contributors. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

using System.Collections.Generic;
using Dapplo.Confluence.Query;

namespace Dapplo.Confluence.Entities
{
    /// <summary>
    ///     Details to perform a search with
    /// </summary>
    public class SearchDetails
    {
        /// <summary>
        /// Default constructor using a IFinalClause
        /// </summary>
        /// <param name="cql">IFinalClause</param>
        public SearchDetails(IFinalClause cql)
        {
            Cql = cql;
        }

        /// <summary>
        /// Specify the Confluence query language
        /// </summary>
        public IFinalClause Cql { get; set; }

        /// <summary>
        /// The context to execute a cql search in, this is the json serialized form of SearchContext
        /// </summary>
        public string CqlContext { get; set; }

        /// <summary>
        /// Specify from where to start returning results, default 0
        /// </summary>
        public int? Start { get; set; }

        /// <summary>
        /// Limit the search to the specified amount, default 20
        /// </summary>
        public int? Limit {get; set; }

        /// <summary>
        /// Specify the search expand values, default is what is specified in the ConfluenceClientConfig.ExpandSearch
        /// </summary>
        public IEnumerable<string> ExpandSearch { get; set; } = ConfluenceClientConfig.ExpandSearch;
    }
}
```

**Comment by tjouinrmld** [comment]
That's perfect ! will scale better this way.
So I let you submit your modification and we close this Pull Request ?

**Comment by Lakritzator** [comment]
I prefer that contributors get the "credit" for their changes, and prefer if they can do as much as they like. I don't want to yank every PR away because "I know better".

The choice is up to you 🤷

**Comment by Lakritzator** [comment]
Today I was touching the code for an issue, and I already made the initial changes I mentioned here.
I hope you are okay with that, I would have given you the "credits" but in this case it just matched the request and it was easier to make only one change to the code.

**Comment by Lakritzator** [comment]
Closing this, as the PR #45 already contains the paging support.

Please have a look at the new build, Dapplo.Confluence 1.0 it should be available later today.
Let me know if that works for you!

**Comment by tjouinrmld** [comment]
Much more complete fix thanks ! Will use latest version of Dapplo.Confluence

**Pull request closed without merging**
